# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v2.2.3
_src_path: gh:FallingColors/hexdummy
advanced: false
description: Another HexCasting addon I guess
display_name: Hyper's Hexcast addon
github_repo: hyper_hexcast
github_user: janIpen
java_package: io.github.janipen.hyperhexcast
mappings_name: Mojmap
minecraft_version_in_mod_version: false
mit_license: true
mod_version: 0.1.0
modid: hyperhexcast
